### ISSUE TITLE
CI for gst-plugins-vision

### ISSUE THREAD

**Issue by 5shekel** [joshdoe/gst-plugins-vision#66]
i quickly made on for ubuntu-latest, let talk about this. it will solve a lot of issues dealing with installation procedure for diff platform. aside from other benefits of CI

```yml
name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install deps
      run: sudo apt-get install libgstreamer-plugins-base1.0-dev liborc-0.4-dev

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory.
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

#     - name: Test
#       working-directory: ${{github.workspace}}/build
#       # Execute tests defined by the CMake configuration.  
#       # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
#       run: ctest -C ${{env.BUILD_TYPE}}
      
```
